In [1]:
# User asked about a TypeError in df["Promo"].str.replace() in cell GvbVZtc3IScR.
# The issue is that the replacement value must be a string, not an integer.
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [19]:
import pandas as pd
from IPython.display import display
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv("/content/drive/MyDrive/[02] Work/BelajarDataScience/Dataset/StudentPerformanceFactorsClean.csv")
display(df.head())
df

folder = "/content/drive/MyDrive/[02] Work/BelajarDataScience/Dataset/"

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Academic_Status
0,23,84,Low,High,No,7,73,Low,Yes,0,...,Medium,Public,Positive,3,No,High School,Near,Male,67,Remidial
1,19,64,Low,Medium,No,8,59,Low,Yes,2,...,Medium,Public,Negative,4,No,College,Moderate,Female,61,Remidial
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,...,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74,Pass
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,...,Medium,Public,Negative,4,No,High School,Moderate,Male,71,Pass
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,...,High,Public,Neutral,4,No,College,Near,Female,70,Pass

In [3]:
df.shape

(6607, 21)

In [4]:
#menghapus data duplikat
print("jumlah data duplikat: ", df.duplicated().sum())
duplikat_semua = df[df.duplicated(keep=False)]
display(duplikat_semua)

jumlah data duplikat:  0

Empty DataFrame
Columns: [Hours_Studied, Attendance, Parental_Involvement, Access_to_Resources, Extracurricular_Activities, Sleep_Hours, Previous_Scores, Motivation_Level, Internet_Access, Tutoring_Sessions, Family_Income, Teacher_Quality, School_Type, Peer_Influence, Physical_Activity, Learning_Disabilities, Parental_Education_Level, Distance_from_Home, Gender, Exam_Score, Academic_Status]
Index: []

[0 rows x 21 columns]

In [5]:
df.isnull().sum()

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
Academic_Status                0
dtype: int64

In [7]:
df = df.dropna()
df.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
Academic_Status               0
dtype: int64

In [8]:
df.shape

(6378, 21)

In [20]:
# Kolom yang ingin dibersihkan
cols = ["Hours_Studied", "Attendance", "Exam_Score"]

# Loop untuk hapus outlier
for col in cols:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    df = df[(df[col] >= lower_bound) & (df[col] <= upper_bound)]

# Simpan ke file baru
df.to_csv(folder + "StudentPerformanceFactorsCleanNew.csv", index=False)

In [23]:
Q1 = df["Hours_Studied"].quantile(0.25)
Q3 = df["Hours_Studied"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier = df[
    (df["Hours_Studied"] < lower_bound) |
     (df["Hours_Studied"] > upper_bound)
]

print("Jumlah Outlier :", len(outlier))
print("Data Outlier")
print(outlier[["Hours_Studied"]])

Jumlah Outlier : 0
Data Outlier
Empty DataFrame
Columns: [Hours_Studied]
Index: []

In [24]:
Q1 = df["Attendance"].quantile(0.25)
Q3 = df["Attendance"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier = df[
    (df["Attendance"] < lower_bound) |
     (df["Attendance"] > upper_bound)
]

print("Jumlah Outlier :", len(outlier))
print("Data Outlier")
print(outlier[["Attendance"]])

Jumlah Outlier : 0
Data Outlier
Empty DataFrame
Columns: [Attendance]
Index: []

In [25]:
Q1 = df["Exam_Score"].quantile(0.25)
Q3 = df["Exam_Score"].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outlier = df[
    (df["Exam_Score"] < lower_bound) |
     (df["Exam_Score"] > upper_bound)
]

print("Jumlah Outlier :", len(outlier))
print("Data Outlier")
print(outlier[["Exam_Score"]])

Jumlah Outlier : 0
Data Outlier
Empty DataFrame
Columns: [Exam_Score]
Index: []