In [83]:
# Linier Regression Model Biaya Kesehatan

import pandas as pd
import numpy as np
import joblib
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.linear_model import LinearRegression
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeRegressor, DecisionTreeClassifier
from sklearn.ensemble import RandomForestRegressor, RandomForestClassifier
from sklearn.neighbors import KNeighborsClassifier


from sklearn.model_selection import train_test_split
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score,
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score,
    f1_score,
    classification_report
)
from sklearn.preprocessing import LabelEncoder, StandardScaler

from google.colab import drive
drive.mount('/content/drive')

folder = "/content/drive/MyDrive/[02] Work/BelajarDataScience/Dataset/"

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [84]:
df=pd.read_csv("/content/drive/MyDrive/[02] Work/BelajarDataScience/Dataset/StudentPerformanceFactorsCleanNew.csv")
display(df)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Academic_Status
0,23,84,Low,High,No,7,73,Low,Yes,0,...,Medium,Public,Positive,3,No,High School,Near,Male,67,Remidial
1,19,64,Low,Medium,No,8,59,Low,Yes,2,...,Medium,Public,Negative,4,No,College,Moderate,Female,61,Remidial
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,...,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74,Pass
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,...,Medium,Public,Negative,4,No,High School,Moderate,Male,71,Pass
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,...,High,Public,Neutral,4,No,College,Near,Female,70,Pass
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6468,25,69,High,Medium,No,7,76,Medium,Yes,1,...,Medium,Public,Positive,2,No,High School,Near,Female,68,Remidial
6469,23,76,High,Medium,No,8,81,Medium,Yes,3,...,High,Public,Positive,2,No,High School,Near,Female,69,Remidial
6470,20,90,Medium,Low,Yes,6,65,Low,Yes,3,...,Medium,Public,Negative,2,No,Postgraduate,Near,Female,68,Remidial
6471,10,86,High,High,Yes,6,91,High,Yes,2,...,Medium,Private,Positive,3,No,High School,Far,Female,68,Remidial
6472,15,67,Medium,Low,Yes,9,94,Medium,Yes,0,...,Medium,Public,Positive,4,No,Postgraduate,Near,Male,64,Remidial

In [85]:
# 2. Pisahkan Feature dan Target
x = df.drop(["Exam_Score", "Academic_Status"], axis=1)
y = df["Academic_Status"]

# Encoding Kategorikal
x = pd.get_dummies(x, drop_first=True)

#Encoding Fitur Kategorikal
le = LabelEncoder()
y = le.fit_transform(y)

# 3. Split Data
x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

In [86]:
# 5. Normalisasi (Penting untuk KNN & Logistic)

scaler = StandardScaler()

x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [87]:
# 6. Membuat Model
model_lr = LogisticRegression(max_iter=1000)
model_knn = KNeighborsClassifier(n_neighbors=5)
model_dt = DecisionTreeClassifier(random_state=42)
model_rf = RandomForestClassifier(n_estimators=100, random_state=42)

In [88]:
# 7. Training

model_lr.fit(x_train, y_train)
model_knn.fit(x_train, y_train)
model_dt.fit(x_train, y_train)
model_rf.fit(x_train, y_train)

RandomForestClassifier(random_state=42)

In [89]:
# 8. Prediksi

pred_lr = model_lr.predict(x_test)
pred_knn = model_knn.predict(x_test)
pred_dt = model_dt.predict(x_test)
pred_rf = model_rf.predict(x_test)

In [90]:
# 9. Evaluasi Model

def evaluasi(nama, y_test, pred):
    acc = accuracy_score(y_test, pred)
    prec = precision_score(y_test, pred, average="weighted")
    rec = recall_score(y_test, pred, average="weighted")
    f1 = f1_score(y_test, pred, average="weighted")

    print("\n====== Hasil Evaluasi Model ======")
    print(f"Model: {nama}")
    print(f"Accuracy: {acc}")
    print(f"Precision: {prec}")
    print(f"Recall: {rec}")
    print(f"F1 Score: {f1}")

    return acc

acc_lr = evaluasi("Logistic Regression", y_test, pred_lr)
acc_knn = evaluasi("K-Nearest Neighbors", y_test, pred_knn)
acc_dt = evaluasi("Decision Tree", y_test, pred_dt)
acc_rf = evaluasi("Random Forest", y_test, pred_rf)

====== Hasil Evaluasi Model ======
Model: Logistic Regression
Accuracy: 0.9776061776061776
Precision: 0.9715546637390325
Recall: 0.9776061776061776
F1 Score: 0.9745704534713562

====== Hasil Evaluasi Model ======
Model: K-Nearest Neighbors
Accuracy: 0.8301158301158301
Precision: 0.8165449019817953
Recall: 0.8301158301158301
F1 Score: 0.8087574892104534

====== Hasil Evaluasi Model ======
Model: Decision Tree
Accuracy: 0.8548262548262548
Precision: 0.856851464877147
Recall: 0.8548262548262548
F1 Score: 0.8557495158981023

====== Hasil Evaluasi Model ======
Model: Random Forest
Accuracy: 0.911969111969112
Precision: 0.9057882553825319
Recall: 0.911969111969112
F1 Score: 0.9057245467940498

/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.12/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))

In [91]:
# 10. Seleksi Model Terbaik

score = {
    "Logistic Regression": acc_lr,
    "K-Nearest Neighbors": acc_knn,
    "Decision Tree": acc_dt,
    "Random Forest": acc_rf
}

model_terbaik_klasifikasi = max(score, key=score.get)
print("\nModel Terbaik: ", model_terbaik_klasifikasi)

Model Terbaik:  Logistic Regression

In [92]:
# 11. Simpan Semua Model

joblib.dump(model_lr, folder + "model_student_logistic_regression_klasifikasi.pkl")
joblib.dump(model_knn, folder + "model_student_knn_klasifikasi.pkl")
joblib.dump(model_dt, folder + "model_student_decision_tree_klasifikasi.pkl")
joblib.dump(model_rf, folder + "model_student_random_forest_klasifikasi.pkl")
print("\nModel berhasil disimpan!")

# Simpan Scaller juga
joblib.dump(scaler, folder + "scaler.pkl")

print("\nSemua model berhasil disimpan!")

Model berhasil disimpan!

Semua model berhasil disimpan!

In [93]:
# 12. Simpan Model Terbaik
if model_terbaik_klasifikasi == "Logistic Regression":
    model_terbaik = model_lr
elif model_terbaik_klasifikasi == "K-Nearest Neighbors":
    model_terbaik = model_knn
elif model_terbaik_klasifikasi == "Decision Tree":
    model_terbaik = model_dt
else:
    model_final_klasifikasi = model_rf

joblib.dump(model_terbaik, folder + "model_student_klasifikasi_terbaik.pkl")
print("\nModel terbaik disimpan!")

Model terbaik disimpan!

In [94]:
# === Prediksi Kategori Status Kelulusan ===
df=pd.read_csv("/content/drive/MyDrive/[02] Work/BelajarDataScience/Dataset/StudentPerformanceFactorsClean.csv")
model = joblib.load(folder + "model_student_klasifikasi_terbaik.pkl")
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6607 entries, 0 to 6606
Data columns (total 21 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               6607 non-null   int64
 1   Attendance                  6607 non-null   int64
 2   Parental_Involvement        6607 non-null   object
 3   Access_to_Resources         6607 non-null   object
 4   Extracurricular_Activities  6607 non-null   object
 5   Sleep_Hours                 6607 non-null   int64
 6   Previous_Scores             6607 non-null   int64
 7   Motivation_Level            6607 non-null   object
 8   Internet_Access             6607 non-null   object
 9   Tutoring_Sessions           6607 non-null   int64
 10  Family_Income               6607 non-null   object
 11  Teacher_Quality             6529 non-null   object
 12  School_Type                 6607 non-null   object
 13  Peer_Influence              6607 non-null   object
 14  Physical_Activity           6607 non-null   int64
 15  Learning_Disabilities       6607 non-null   object
 16  Parental_Education_Level    6517 non-null   object
 17  Distance_from_Home          6540 non-null   object
 18  Gender                      6607 non-null   object
 19  Exam_Score                  6607 non-null   int64
 20  Academic_Status             6607 non-null   object
dtypes: int64(7), object(14)
memory usage: 1.1+ MB

In [95]:
# Feature referensi (harus sama dengan training)

x_ref = pd.get_dummies(
    df.drop(["Exam_Score", "Academic_Status"], axis=1), drop_first=True)

y_true = df["Academic_Status"]

In [96]:
# Hitung Kesalahan Model
y_pred_all = model.predict(x_ref)

# Definisikan pemetaan dari label string ke label numerik
# Pemetaan ini selaras dengan keluaran numerik yang diharapkan dari model
label_map_reverse = {
    "Fail" : 0,
    "Remidial" : 1,
    "Pass" : 2
}

# Convert y_true (string labels) to numerical lebels
y_true_numeric = y_true.map(label_map_reverse)

accuracy = accuracy_score(y_true_numeric, y_pred_all)
error_rate = 1 - accuracy
cm = confusion_matrix(y_true_numeric, y_pred_all)

print("\n=== Evaluasi Model Global ===")
print(f"Accuracy Model: {accuracy:.3f}")
print(f"Error Rate: {error_rate:.3f}")
print("\n=== Confusion Matrix ===")
print(cm)

=== Evaluasi Model Global ===
Accuracy Model: 0.744
Error Rate: 0.256

=== Confusion Matrix ===
[[   0   68    0]
 [   0 4914    0]
 [   0 1625    0]]

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(

In [97]:
# Membaca Input Dari User

print("\n====== Masukkan Data Baru ======")
hour_studied = int(input("Durasi Belajar (Jam) : "))
attendance = int(input("Prosentase Kehadiran (%) : "))
extracurricular_activities = input("Ikut Kegiatan Ekstra (Yes/No) : ")
previous_scores = int(input("Nilai Sebelumnya (0-100) : "))
internet_access = input("Kepemilikan Akses Internet (Yes/No) : ")
tutoring_sessions = int(input("Jumlah sesi bimbingan belajar (les/tutor) yang diikuti siswa : "))
peer_influence = input("Pengaruh Teman Sebaya (Positive/Negative) : ")
physical_activity = int(input("Frekuensi Aktivitas Fisik Siswa (Jam/Minggu) : "))
parental_education_level = input("Tingkat pendidikan orang tua siswa (High School/College/Postgraduate) : ")
distance_from_home = input("Jarak ke sekolah (Near/Moderate/Far) : ")

# Buat Dataframe Input

input_data = {
    "Hours_Studied": [hour_studied],
    "Attendance": [attendance],
    "Extracurricular_Activities": [extracurricular_activities],
    "Previous_Scores": [previous_scores],
    "Internet_Access": [internet_access],
    "Tutoring_Sessions": [tutoring_sessions],
    "Peer_Influence": [peer_influence],
    "Physical_Activity": [physical_activity],
    "Parental_Education_Level": [parental_education_level],
    "Distance_From_Home": [distance_from_home]
}

# Encoding
input_df = pd.DataFrame(input_data)
display(input_df)

# Samakan Kolom
input_df = input_df.reindex(columns=x.columns, fill_value=0)

====== Masukkan Data Baru ======
Durasi Belajar (Jam) : 24
Prosentase Kehadiran (%) : 98
Ikut Kegiatan Ekstra (Yes/No) : Yes
Nilai Sebelumnya (0-100) : 91
Kepemilikan Akses Internet (Yes/No) : Yes
Jumlah sesi bimbingan belajar (les/tutor) yang diikuti siswa : 2
Pengaruh Teman Sebaya (Positive/Negative) : Positive
Frekuensi Aktivitas Fisik Siswa (Jam/Minggu) : 2
Tingkat pendidikan orang tua siswa (High School/College/Postgraduate) : Postgraduate
Jarak ke sekolah (Near/Moderate/Far) : Near

,Hours_Studied,Attendance,Extracurricular_Activities,Previous_Scores,Internet_Access,Tutoring_Sessions,Peer_Influence,Physical_Activity,Parental_Education_Level,Distance_From_Home
0,24,98,Yes,91,Yes,2,Positive,2,Postgraduate,Near

In [99]:
# Prediksi Kategori
prediksi_kategori = model.predict(input_df)[0]

# Definisikan pemetaan dari label numerik ke label string
label_map = {
    0: "Fail",
    1: "Remidial",
    2: "Pass"
}

print("\n=== Hasil Prediksi ===")
print(f"Kategori Kelulusan: {label_map[prediksi_kategori]}")
print(f"Tingkat kesalahan model (Error Rate): +-{error_rate*100:.2f}%")

=== Hasil Prediksi ===
Kategori Kelulusan: Remidial
Tingkat kesalahan model (Error Rate): +-25.62%

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LogisticRegression was fitted without feature names
  warnings.warn(